In [1]:
import numpy as np
array1=np.array([[2,3,4,5],[1,7,6,9]])
print(array1)

[[2 3 4 5]
 [1 7 6 9]]


In [2]:
print(type(array1))

<class 'numpy.ndarray'>


In [3]:
array1.shape

(2, 4)

In [4]:
array1.dtype

dtype('int32')

In [5]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
array1

array([[2, 3, 4, 5],
       [1, 7, 6, 9]])

In [9]:
array1*array1

array([[ 4,  9, 16, 25],
       [ 1, 49, 36, 81]])

In [10]:
1/array1

array([[0.5       , 0.33333333, 0.25      , 0.2       ],
       [1.        , 0.14285714, 0.16666667, 0.11111111]])

# slicing

In [17]:
array2=np.array([5,6,7,8])

In [20]:
arr=array2[4:6].copy()

In [19]:
arr

array([], dtype=int32)

In [21]:
array2

array([5, 6, 7, 8])