In [1]:
import numpy as np

In [2]:
a=np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [14]:
b=np.array([1,2,3,4,5,6,7,8,9,9,45,46,43,56,76,8,87,66])
b=b.reshape(6,3)

In [15]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 9, 45, 46],
       [43, 56, 76],
       [ 8, 87, 66]])

In [20]:
np.argsort(b,axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [5, 3, 3],
       [3, 4, 5],
       [4, 5, 4]], dtype=int64)

In [17]:
np.argmin(b)

0

In [18]:
np.argmax(b)

16